################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_cad_hw_if.c \
/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_hw.c \
/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_hw_if_it.c \
/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_phy.c \
/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_phy_hw_if.c \
/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_pwr_hw_if.c \
/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_timersserver.c \
/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Core/src/usbpd_trace.c 

OBJS += \
./Middlewares/USBPD/usbpd_cad_hw_if.o \
./Middlewares/USBPD/usbpd_hw.o \
./Middlewares/USBPD/usbpd_hw_if_it.o \
./Middlewares/USBPD/usbpd_phy.o \
./Middlewares/USBPD/usbpd_phy_hw_if.o \
./Middlewares/USBPD/usbpd_pwr_hw_if.o \
./Middlewares/USBPD/usbpd_timersserver.o \
./Middlewares/USBPD/usbpd_trace.o 

C_DEPS += \
./Middlewares/USBPD/usbpd_cad_hw_if.d \
./Middlewares/USBPD/usbpd_hw.d \
./Middlewares/USBPD/usbpd_hw_if_it.d \
./Middlewares/USBPD/usbpd_phy.d \
./Middlewares/USBPD/usbpd_phy_hw_if.d \
./Middlewares/USBPD/usbpd_pwr_hw_if.d \
./Middlewares/USBPD/usbpd_timersserver.d \
./Middlewares/USBPD/usbpd_trace.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/USBPD/usbpd_cad_hw_if.o: /Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_cad_hw_if.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSBPD_PORT_COUNT=1 -D_RTOS -DUSE_HAL_DRIVER -DSTM32G431xx -D_SNK -DUSBPDCORE_LIB_PD3_CONFIG_1 -c -I../Core/Inc -I../USBPD/App -I../USBPD -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/asserv" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/callBack" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/shell" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/changeMode" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/Lidar" -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Core/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Device/ST/STM32G4xx/Include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/USBPD/usbpd_hw.o: /Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_hw.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSBPD_PORT_COUNT=1 -D_RTOS -DUSE_HAL_DRIVER -DSTM32G431xx -D_SNK -DUSBPDCORE_LIB_PD3_CONFIG_1 -c -I../Core/Inc -I../USBPD/App -I../USBPD -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/asserv" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/callBack" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/shell" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/changeMode" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/Lidar" -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Core/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Device/ST/STM32G4xx/Include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/USBPD/usbpd_hw_if_it.o: /Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_hw_if_it.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSBPD_PORT_COUNT=1 -D_RTOS -DUSE_HAL_DRIVER -DSTM32G431xx -D_SNK -DUSBPDCORE_LIB_PD3_CONFIG_1 -c -I../Core/Inc -I../USBPD/App -I../USBPD -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/asserv" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/callBack" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/shell" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/changeMode" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/Lidar" -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Core/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Device/ST/STM32G4xx/Include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/USBPD/usbpd_phy.o: /Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_phy.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSBPD_PORT_COUNT=1 -D_RTOS -DUSE_HAL_DRIVER -DSTM32G431xx -D_SNK -DUSBPDCORE_LIB_PD3_CONFIG_1 -c -I../Core/Inc -I../USBPD/App -I../USBPD -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/asserv" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/callBack" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/shell" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/changeMode" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/Lidar" -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Core/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Device/ST/STM32G4xx/Include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/USBPD/usbpd_phy_hw_if.o: /Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_phy_hw_if.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSBPD_PORT_COUNT=1 -D_RTOS -DUSE_HAL_DRIVER -DSTM32G431xx -D_SNK -DUSBPDCORE_LIB_PD3_CONFIG_1 -c -I../Core/Inc -I../USBPD/App -I../USBPD -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/asserv" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/callBack" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/shell" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/changeMode" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/Lidar" -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Core/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Device/ST/STM32G4xx/Include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/USBPD/usbpd_pwr_hw_if.o: /Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_pwr_hw_if.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSBPD_PORT_COUNT=1 -D_RTOS -DUSE_HAL_DRIVER -DSTM32G431xx -D_SNK -DUSBPDCORE_LIB_PD3_CONFIG_1 -c -I../Core/Inc -I../USBPD/App -I../USBPD -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/asserv" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/callBack" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/shell" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/changeMode" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/Lidar" -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Core/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Device/ST/STM32G4xx/Include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/USBPD/usbpd_timersserver.o: /Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/src/usbpd_timersserver.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSBPD_PORT_COUNT=1 -D_RTOS -DUSE_HAL_DRIVER -DSTM32G431xx -D_SNK -DUSBPDCORE_LIB_PD3_CONFIG_1 -c -I../Core/Inc -I../USBPD/App -I../USBPD -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/asserv" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/callBack" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/shell" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/changeMode" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/Lidar" -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Core/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Device/ST/STM32G4xx/Include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/USBPD/usbpd_trace.o: /Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Core/src/usbpd_trace.c Middlewares/USBPD/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSBPD_PORT_COUNT=1 -D_RTOS -DUSE_HAL_DRIVER -DSTM32G431xx -D_SNK -DUSBPDCORE_LIB_PD3_CONFIG_1 -c -I../Core/Inc -I../USBPD/App -I../USBPD -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/asserv" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/callBack" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/shell" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/changeMode" -I"/Users/romingo/Desktop/ENSEA/3A/PROJET/2425_ESE_Projet_Tom_et_Jerry/software/Tom_n_Jerry_RTOS/Lidar" -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Core/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G4XX/inc -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Device/ST/STM32G4xx/Include -I/Users/romingo/STM32Cube/Repository/STM32Cube_FW_G4_V1.6.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-USBPD

clean-Middlewares-2f-USBPD:
	-$(RM) ./Middlewares/USBPD/usbpd_cad_hw_if.cyclo ./Middlewares/USBPD/usbpd_cad_hw_if.d ./Middlewares/USBPD/usbpd_cad_hw_if.o ./Middlewares/USBPD/usbpd_cad_hw_if.su ./Middlewares/USBPD/usbpd_hw.cyclo ./Middlewares/USBPD/usbpd_hw.d ./Middlewares/USBPD/usbpd_hw.o ./Middlewares/USBPD/usbpd_hw.su ./Middlewares/USBPD/usbpd_hw_if_it.cyclo ./Middlewares/USBPD/usbpd_hw_if_it.d ./Middlewares/USBPD/usbpd_hw_if_it.o ./Middlewares/USBPD/usbpd_hw_if_it.su ./Middlewares/USBPD/usbpd_phy.cyclo ./Middlewares/USBPD/usbpd_phy.d ./Middlewares/USBPD/usbpd_phy.o ./Middlewares/USBPD/usbpd_phy.su ./Middlewares/USBPD/usbpd_phy_hw_if.cyclo ./Middlewares/USBPD/usbpd_phy_hw_if.d ./Middlewares/USBPD/usbpd_phy_hw_if.o ./Middlewares/USBPD/usbpd_phy_hw_if.su ./Middlewares/USBPD/usbpd_pwr_hw_if.cyclo ./Middlewares/USBPD/usbpd_pwr_hw_if.d ./Middlewares/USBPD/usbpd_pwr_hw_if.o ./Middlewares/USBPD/usbpd_pwr_hw_if.su ./Middlewares/USBPD/usbpd_timersserver.cyclo ./Middlewares/USBPD/usbpd_timersserver.d ./Middlewares/USBPD/usbpd_timersserver.o ./Middlewares/USBPD/usbpd_timersserver.su ./Middlewares/USBPD/usbpd_trace.cyclo ./Middlewares/USBPD/usbpd_trace.d ./Middlewares/USBPD/usbpd_trace.o ./Middlewares/USBPD/usbpd_trace.su

.PHONY: clean-Middlewares-2f-USBPD

